[GameWorld]
# managed by `set map`
name=AlphaGSM World
difficulty=1
gameMode=1
enemyPoolSizeRate=1

[Host]
# managed by `set port`, `set serverpassword`, and `set bindaddress`
port=8787
maxPlayerNumber=8
usePassword=0
serverPassword=00000000
bindAddress=0.0.0.0

[Graphics]
vSyncCount=0
maxFPS=60
grassBend=0
clothSimOption=2

[Save]
autoSaveSec=300
autoSavePerHour=1
savePath=DedicatedServerSave/

[CreativeModeSetting]
quickCraft=1
ageLevel=9
islandLevel=-1
noDeath=1
noDamage=1
noHunger=1
infinitStamina=1
forceDayTime=-1
buildingIgnoreDamage=0
noBuild=0

[CreativeModePlStatus]
Level=0
Health=0
Mana=0
Stamina=0
Money=1000
SkillPoint=0
EnchantPoint=0
