#!/usr/bin/python3
import downloader
import sys
import contextlib

with contextlib.redirect_stdout(sys.stderr):
  try:
    path=downloader.main(sys.argv[1],sys.argv[2:])
  except downloader.DownloaderError as ex:
    print(ex)
    sys.exit(ex.ret)
print(path)
sys.exit(0)
