#!/usr/bin/python3
import os
import sys
import contextlib
from urllib.parse import quote

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import downloader

with contextlib.redirect_stdout(sys.stderr):
    try:
        path=downloader.main(sys.argv[1],sys.argv[2:])
    except downloader.DownloaderError as ex:
        print(ex)
        sys.exit(ex.ret)
print(quote(path))
sys.exit(0)
