#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import core  # pylint: disable=wrong-import-position

if int(sys.argv[1]):
    print("#%AlphaGSM-INTERNAL%#", flush=True)

sys.exit(core.main(sys.argv[2], sys.argv[3:]))
