#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import core as core  # pylint: disable=wrong-import-position

sys.exit(core.main(sys.argv[0], sys.argv[1:]))
