#!/usr/bin/env python3
import contextlib
import os
import sys
from urllib.parse import quote

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import downloader  # pylint: disable=wrong-import-position

with contextlib.redirect_stdout(sys.stderr):
    try:
        path = downloader.main(sys.argv[1], sys.argv[2:])
    except downloader.DownloaderError as ex:
        print(ex)
        sys.exit(ex.ret)
print(quote(path))
sys.exit(0)
