[Server]
welcometext=Welcome to AlphaGSM Mumble
port=64738
host=0.0.0.0
# managed by `set maxplayers`
users=100
database=mumble-server.sqlite
# managed by `set serverpassword`
serverpassword=

[Ice]
; Enable Ice for remote administration if needed
Ice=0
IceWarnUnknownProperties=1

[Logs]
logdays=31
logfile=mumble-server.log

[Security]
sslCert=
sslKey=
sslDHParams=
