[/Script/Engine.GameNetworkManager]
MaxDynamicBandwidth=7000
TotalNetBandwidth=50000
MinDynamicBandwidth=4000

[/Script/ROGame.ROGameInfoTerritories]
RoundTimeLimit=600
bCampaignGame=False

[/Script/Engine.GameReplicationInfo]
ServerName=AlphaGSM Rising Storm 2 Server

; AlphaGSM module defaults and launch values:
; Start map: VNTE-CuChi
; Max players: 64
; Game port: 7777
; Query port: 27015