"""Static contracts for shared game-module unit-test helpers."""

import ast
from pathlib import Path

import pytest


SHARED_HELPER_MODULE = "tests.unit_tests.gamemodules.helpers"
MIGRATED_TEST_MODULES = (
    Path("tests/unit_tests/gamemodules/test_ut3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ut2k4server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ut2k4server_mods.py"),
    Path("tests/unit_tests/gamemodules/test_unturned_cov.py"),
    Path("tests/unit_tests/gamemodules/test_twserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ark_cov.py"),
    Path("tests/unit_tests/gamemodules/test_necserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mumbleserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_notdserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_tuserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_redmserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ns2cserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ns2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ohdserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_onsetserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_outpostzeroserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_pathoftitansserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_pcars2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_pcarserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_pixarkserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_police1013server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_projectzomboid_cov.py"),
    Path("tests/unit_tests/gamemodules/test_pvrserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_q2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_readyornotserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_reignofdwarfserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_reignofkingsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_remnantsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_returntomoriaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_rimworldtogetherserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ror2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_roserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_rs2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_rust_cov.py"),
    Path("tests/unit_tests/gamemodules/test_rwserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_saleblazersserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sampserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_satisfactory_cov.py"),
    Path("tests/unit_tests/gamemodules/test_scpslserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_scumserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_seserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sevendaystodie_cov.py"),
    Path("tests/unit_tests/gamemodules/test_silicaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_skyrimtogetherrebornserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_smallandserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sniperelite4server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sof2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_solserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sonsoftheforestserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_squad44server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_squadserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ss14server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_starruptureserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_stationeersserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_staxelserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_stormworksserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_stnserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_subnauticaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_subsistenceserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sunkenlandserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_teamfortress2_cov.py"),
    Path("tests/unit_tests/gamemodules/test_terratechworldsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_tf2cserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_theforestserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_thefrontserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_tiserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_trackmaniaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ts3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ut99server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_veinserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_vintagestoryserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_vrserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_warbandserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_wetserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_wreckfestserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_wurmserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_xntserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_abfserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_accserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_acserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_alienarenaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_aloftserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_argoserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arksurvivalascended_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma2coserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3altislifeserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3desolationreduxserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3epochserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3exileserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3headlessserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_arma3wastelandserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_armarserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_askaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_astroneerserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_atlasserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_atsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_bannerlordserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_battlebitserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_battlecryoffreedomserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_bf1942server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_bfvserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_blackops3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_blackwakeserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_bobserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_brickadiaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_brokeprotocolserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_btlserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_chivalryserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_citadelserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ckserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_cod2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_cod4server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_codserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_coduoserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_codwawserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_colserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_conanexiles_cov.py"),
    Path("tests/unit_tests/gamemodules/test_counterstrike2_cov.py"),
    Path("tests/unit_tests/gamemodules/test_counterstrikeglobaloffensive_cov.py"),
    Path("tests/unit_tests/gamemodules/test_craftopiaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_cryofallserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_darkandlightserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_dayofdragonsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_dayzarma2epochserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_dayzserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_deadmatterserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_deadpolyserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_dstserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ducksideserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ecoserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_empyrionserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_enshrouded_cov.py"),
    Path("tests/unit_tests/gamemodules/test_etlegacyserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_ets2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_exfilserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_fearthenightserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_foundryserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_frozenflameserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_goldeneyesourceserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_gravserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_groundbranchserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_hcuserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_heatserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_hellletlooseserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_hogwarpserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_hurtworldserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_hzserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_icarusserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_identityserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_inssserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_interstellarriftserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_jc2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_jc3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_jk2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_kerbalspaceprogramserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_kf2server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_lastoasisserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_longvinterserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_medievalengineersserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_memoriesofmarsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_miscreatedserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_gtafivemserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_kfserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mohaaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mordserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_motortownserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mtaserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mw3server_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mxbikesserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_mythofempiresserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_nightingale_cov.py"),
    Path("tests/unit_tests/gamemodules/test_noonesurvivedserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_palworld_cov.py"),
    Path("tests/unit_tests/gamemodules/test_primalcarnageextinctionserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_rtcwserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_sbotsserver_cov.py"),
    Path("tests/unit_tests/gamemodules/test_soulmask_cov.py"),
    Path("tests/unit_tests/gamemodules/test_wfserver_cov.py"),
)


@pytest.mark.parametrize("test_module", MIGRATED_TEST_MODULES)
def test_migrated_modules_use_shared_server_double(test_module):
    tree = ast.parse(test_module.read_text(encoding="utf-8"))
    local_classes = {
        node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)
    }
    shared_imports = {
        alias.name
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom) and node.module == SHARED_HELPER_MODULE
        for alias in node.names
    }

    assert "DummyData" not in local_classes
    assert "DummyServer" not in local_classes
    assert "DummyServer" in shared_imports
