[Engine.GameEngine]
ServerName=AlphaGSM Red Orchestra Server
CacheSizeMegs=32

[IpDrv.TcpNetDriver]
Port=7757
MaxClientRate=20000
InitialConnectTimeout=200.0
ConnectionTimeout=15.0

[Engine.AccessControl]
AdminPassword=
GamePassword=

; AlphaGSM module defaults and launch values:
; Start map: Ostfront-Rakowice
; Game type: ROEngine.ROTeamGame
; Log file: server.log